# Generated by Django 4.1.2 on 2022-10-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog_api', '0002_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='publication_date',
            field=models.DateField(),
        ),
    ]
